// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace convertizzle.Migrations
{
    [DbContext(typeof(CCContext))]
    partial class CCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("convertizzle.Models.Account", b =>
                {
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApiKey");

                    b.Property<int>("Credits");

                    b.HasKey("Email");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("convertizzle.Models.Conversion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountEmail");

                    b.Property<TimeSpan>("ConversionDuration");

                    b.Property<DateTime?>("ConversionEnded");

                    b.Property<DateTime>("ConversionStarted");

                    b.Property<double>("ConvertedContentSize");

                    b.Property<string>("ExceptionDetails");

                    b.Property<string>("Filename");

                    b.Property<double>("OriginalContentSize");

                    b.Property<bool>("Succeeded");

                    b.HasKey("Id");

                    b.HasIndex("AccountEmail");

                    b.ToTable("Conversions");
                });

            modelBuilder.Entity("convertizzle.Models.Conversion", b =>
                {
                    b.HasOne("convertizzle.Models.Account", "Account")
                        .WithMany("Conversions")
                        .HasForeignKey("AccountEmail");
                });
#pragma warning restore 612, 618
        }
    }
}
